In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("MSE 446 - Raw Project Data.csv")
print(df.head())

   listing_id        date  vacant_days  reserved_days  occupancy  revenue  \
0     4925824  2025-02-01           28              0        0.0        0
1     4925824  2025-03-01           31              0        0.0        0
2     4925824  2025-04-01           30              0        0.0        0
3     4925824  2025-05-01           31              0        0.0        0
4     4925824  2025-06-01           30              0        0.0        0

  rate_avg               listing_type     room_type  photos_count  ...  \
0     36.3  Private room in townhouse  private_room             7  ...
1     35.5  Private room in townhouse  private_room             7  ...
2     35.9  Private room in townhouse  private_room             7  ...
3       36  Private room in townhouse  private_room             7  ...
4     36.5  Private room in townhouse  private_room             7  ...

   rain_s  snow_v  snow_s  snow_on_ground_v  non_resident_visitors  \
0   17.62   28.99   17.56               6.4                 197392
1   21.35   16.94   12.79               3.0                 251406
2   29.82    4.93    5.76               0.5                 322508
3   33.46    0.13    0.58               0.0                 384863
4   39.88    0.00    0.00               0.0                 514456

   Unnamed: 88  Unnamed: 89 Unnamed: 90  Unnamed: 91 Unnamed: 92
0          NaN          NaN         NaN          NaN         NaN
1          NaN          NaN         NaN          NaN         NaN
2          NaN          NaN         NaN          NaN         NaN
3          NaN          NaN         NaN          NaN         NaN
4          NaN          NaN         NaN          NaN         NaN

[5 rows x 93 columns]

In [5]:
print(df.shape)
print(df.columns.tolist())
df.info()
df.head()

(3236, 93)
['listing_id', 'date', 'vacant_days', 'reserved_days', 'occupancy', 'revenue', 'rate_avg', 'listing_type', 'room_type', 'photos_count', 'superhost', 'latitude', 'longitude', 'guests', 'bedrooms', 'beds', 'baths', 'amenities', 'min_nights', 'cancellation_policy', 'cleaning_fee', 'extra_guest_fee', 'num_reviews', 'rating_overall', 'rating_accuracy', 'rating_checkin', 'rating_cleanliness', 'rating_communication', 'rating_location', 'rating_value', 'ttm_revenue', 'ttm_revenue_native', 'ttm_avg_rate', 'ttm_avg_rate_native', 'ttm_occupancy', 'ttm_adjusted_occupancy', 'ttm_revpar', 'ttm_revpar_native', 'ttm_adjusted_revpar', 'ttm_adjusted_revpar_native', 'ttm_reserved_days', 'ttm_blocked_days', 'ttm_available_days', 'ttm_total_days', 'l90d_revenue', 'l90d_revenue_native', 'l90d_avg_rate', 'l90d_avg_rate_native', 'l90d_occupancy', 'l90d_adjusted_occupancy', 'l90d_revpar', 'l90d_revpar_native', 'l90d_adjusted_revpar', 'l90d_adjusted_revpar_native', 'l90d_reserved_days', 'l90d_blocked_days', 'l90d_available_days', 'l90d_total_days', 'Hotel_Occupancy_Percentage', 'Average_Daily_Rate', 'Revenue_Per_Available_Room', 'is_winter', 'is_spring', 'is_summer', 'is_fall', 'num_public_holidays', 'num_major_events', 'nba_season', 'nhl_season', 'mlb_season', 'max_dew_point_v', 'max_relative_humidity_v', 'max_temperature_v', 'max_temperature_s', 'max_wind_speed_v', 'min_dew_point_v', 'min_relative_humidity_v', 'min_temperature_v', 'min_temperature_s', 'min_wind_speed_v', 'precipitation_v', 'precipitation_s', 'rain_v', 'rain_s', 'snow_v', 'snow_s', 'snow_on_ground_v', 'non_resident_visitors', 'Unnamed: 88', 'Unnamed: 89', 'Unnamed: 90', 'Unnamed: 91', 'Unnamed: 92']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3236 entries, 0 to 3235
Data columns (total 93 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   listing_id                   3236 non-null   int64
 1   date                         3236 non-null   object
 2   vacant_days                  3236 non-null   int64
 3   reserved_days                3236 non-null   int64
 4   occupancy                    3236 non-null   float64
 5   revenue                      3236 non-null   int64
 6   rate_avg                     3236 non-null   object
 7   listing_type                 3236 non-null   object
 8   room_type                    3236 non-null   object
 9   photos_count                 3236 non-null   int64
 10  superhost                    3236 non-null   bool
 11  latitude                     3236 non-null   float64
 12  longitude                    3236 non-null   float64
 13  guests                       3236 non-null   int64
 14  bedrooms                     3236 non-null   int64
 15  beds                         3236 non-null   int64
 16  baths                        3236 non-null   float64
 17  amenities                    3236 non-null   object
 18  min_nights                   3236 non-null   int64
 19  cancellation_policy          3236 non-null   object
 20  cleaning_fee                 3236 non-null   int64
 21  extra_guest_fee              3236 non-null   int64
 22  num_reviews                  3236 non-null   int64
 23  rating_overall               3236 non-null   float64
 24  rating_accuracy              3236 non-null   float64
 25  rating_checkin               3236 non-null   float64
 26  rating_cleanliness           3236 non-null   float64
 27  rating_communication         3236 non-null   float64
 28  rating_location              3236 non-null   float64
 29  rating_value                 3236 non-null   float64
 30  ttm_revenue                  3236 non-null   int64
 31  ttm_revenue_native           3236 non-null   int64
 32  ttm_avg_rate                 3236 non-null   float64
 33  ttm_avg_rate_native          3236 non-null   float64
 34  ttm_occupancy                3236 non-null   float64
 35  ttm_adjusted_occupancy       3236 non-null   float64
 36  ttm_revpar                   3236 non-null   float64
 37  ttm_revpar_native            3236 non-null   float64
 38  ttm_adjusted_revpar          3236 non-null   float64
 39  ttm_adjusted_revpar_native   3236 non-null   float64
 40  ttm_reserved_days            3236 non-null   int64
 41  ttm_blocked_days             3236 non-null   int64
 42  ttm_available_days           3236 non-null   int64
 43  ttm_total_days               3236 non-null   int64
 44  l90d_revenue                 3236 non-null   int64
 45  l90d_revenue_native          3236 non-null   int64
 46  l90d_avg_rate                3236 non-null   float64
 47  l90d_avg_rate_native         3236 non-null   float64
 48  l90d_occupancy               3236 non-null   float64
 49  l90d_adjusted_occupancy      3236 non-null   float64
 50  l90d_revpar                  3236 non-null   float64
 51  l90d_revpar_native           3236 non-null   float64
 52  l90d_adjusted_revpar         3236 non-null   float64
 53  l90d_adjusted_revpar_native  3236 non-null   float64
 54  l90d_reserved_days           3236 non-null   int64
 55  l90d_blocked_days            3236 non-null   int64
 56  l90d_available_days          3236 non-null   int64
 57  l90d_total_days              3236 non-null   int64
 58  Hotel_Occupancy_Percentage   3236 non-null   float64
 59  Average_Daily_Rate           3236 non-null   float64
 60  Revenue_Per_Available_Room   3236 non-null   float64
 61  is_winter                    3236 non-null   int64
 62  is_spring                    3236 non-null   int64
 63  is_summer                    3236 non-null   int64
 64  is_fall                      3236 non-null   int64
 65  num_public_holidays          3236 non-null   int64
 66  num_major_events             3236 non-null   int64
 67  nba_season                   3236 non-null   int64
 68  nhl_season                   3236 non-null   int64
 69  mlb_season                   3236 non-null   int64
 70  max_dew_point_v              3236 non-null   float64
 71  max_relative_humidity_v      3236 non-null   float64
 72  max_temperature_v            3236 non-null   float64
 73  max_temperature_s            3236 non-null   float64
 74  max_wind_speed_v             3236 non-null   float64
 75  min_dew_point_v              3236 non-null   float64
 76  min_relative_humidity_v      3236 non-null   float64
 77  min_temperature_v            3236 non-null   float64
 78  min_temperature_s            3236 non-null   float64
 79  min_wind_speed_v             3236 non-null   float64
 80  precipitation_v              3236 non-null   float64
 81  precipitation_s              3236 non-null   float64
 82  rain_v                       3236 non-null   float64
 83  rain_s                       3236 non-null   float64
 84  snow_v                       3236 non-null   float64
 85  snow_s                       3236 non-null   float64
 86  snow_on_ground_v             3236 non-null   float64
 87  non_resident_visitors        3236 non-null   int64
 88  Unnamed: 88                  0 non-null      float64
 89  Unnamed: 89                  0 non-null      float64
 90  Unnamed: 90                  0 non-null      float64
 91  Unnamed: 91                  0 non-null      float64
 92  Unnamed: 92                  1 non-null      object
dtypes: bool(1), float64(51), int64(34), object(7)
memory usage: 2.3+ MB

,listing_id,date,vacant_days,reserved_days,occupancy,revenue,rate_avg,listing_type,room_type,photos_count,...,rain_s,snow_v,snow_s,snow_on_ground_v,non_resident_visitors,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92
0,4925824,2025-02-01,28,0,0.0,0,36.3,Private room in townhouse,private_room,7,...,17.62,28.99,17.56,6.4,197392,NaN,NaN,NaN,NaN,NaN
1,4925824,2025-03-01,31,0,0.0,0,35.5,Private room in townhouse,private_room,7,...,21.35,16.94,12.79,3.0,251406,NaN,NaN,NaN,NaN,NaN
2,4925824,2025-04-01,30,0,0.0,0,35.9,Private room in townhouse,private_room,7,...,29.82,4.93,5.76,0.5,322508,NaN,NaN,NaN,NaN,NaN
3,4925824,2025-05-01,31,0,0.0,0,36,Private room in townhouse,private_room,7,...,33.46,0.13,0.58,0.0,384863,NaN,NaN,NaN,NaN,NaN
4,4925824,2025-06-01,30,0,0.0,0,36.5,Private room in townhouse,private_room,7,...,39.88,0.00,0.00,0.0,514456,NaN,NaN,NaN,NaN,NaN

In [ ]:
# remove empty columns
df = df.drop(columns=["Unnamed: 88","Unnamed: 89","Unnamed: 90","Unnamed: 91","Unnamed: 92"])

In [12]:
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3236 entries, 0 to 3235
Data columns (total 88 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   listing_id                   3236 non-null   int64
 1   date                         3236 non-null   object
 2   vacant_days                  3236 non-null   int64
 3   reserved_days                3236 non-null   int64
 4   occupancy                    3236 non-null   float64
 5   revenue                      3236 non-null   int64
 6   rate_avg                     3236 non-null   object
 7   listing_type                 3236 non-null   object
 8   room_type                    3236 non-null   object
 9   photos_count                 3236 non-null   int64
 10  superhost                    3236 non-null   bool
 11  latitude                     3236 non-null   float64
 12  longitude                    3236 non-null   float64
 13  guests                       3236 non-null   int64
 14  bedrooms                     3236 non-null   int64
 15  beds                         3236 non-null   int64
 16  baths                        3236 non-null   float64
 17  amenities                    3236 non-null   object
 18  min_nights                   3236 non-null   int64
 19  cancellation_policy          3236 non-null   object
 20  cleaning_fee                 3236 non-null   int64
 21  extra_guest_fee              3236 non-null   int64
 22  num_reviews                  3236 non-null   int64
 23  rating_overall               3236 non-null   float64
 24  rating_accuracy              3236 non-null   float64
 25  rating_checkin               3236 non-null   float64
 26  rating_cleanliness           3236 non-null   float64
 27  rating_communication         3236 non-null   float64
 28  rating_location              3236 non-null   float64
 29  rating_value                 3236 non-null   float64
 30  ttm_revenue                  3236 non-null   int64
 31  ttm_revenue_native           3236 non-null   int64
 32  ttm_avg_rate                 3236 non-null   float64
 33  ttm_avg_rate_native          3236 non-null   float64
 34  ttm_occupancy                3236 non-null   float64
 35  ttm_adjusted_occupancy       3236 non-null   float64
 36  ttm_revpar                   3236 non-null   float64
 37  ttm_revpar_native            3236 non-null   float64
 38  ttm_adjusted_revpar          3236 non-null   float64
 39  ttm_adjusted_revpar_native   3236 non-null   float64
 40  ttm_reserved_days            3236 non-null   int64
 41  ttm_blocked_days             3236 non-null   int64
 42  ttm_available_days           3236 non-null   int64
 43  ttm_total_days               3236 non-null   int64
 44  l90d_revenue                 3236 non-null   int64
 45  l90d_revenue_native          3236 non-null   int64
 46  l90d_avg_rate                3236 non-null   float64
 47  l90d_avg_rate_native         3236 non-null   float64
 48  l90d_occupancy               3236 non-null   float64
 49  l90d_adjusted_occupancy      3236 non-null   float64
 50  l90d_revpar                  3236 non-null   float64
 51  l90d_revpar_native           3236 non-null   float64
 52  l90d_adjusted_revpar         3236 non-null   float64
 53  l90d_adjusted_revpar_native  3236 non-null   float64
 54  l90d_reserved_days           3236 non-null   int64
 55  l90d_blocked_days            3236 non-null   int64
 56  l90d_available_days          3236 non-null   int64
 57  l90d_total_days              3236 non-null   int64
 58  Hotel_Occupancy_Percentage   3236 non-null   float64
 59  Average_Daily_Rate           3236 non-null   float64
 60  Revenue_Per_Available_Room   3236 non-null   float64
 61  is_winter                    3236 non-null   int64
 62  is_spring                    3236 non-null   int64
 63  is_summer                    3236 non-null   int64
 64  is_fall                      3236 non-null   int64
 65  num_public_holidays          3236 non-null   int64
 66  num_major_events             3236 non-null   int64
 67  nba_season                   3236 non-null   int64
 68  nhl_season                   3236 non-null   int64
 69  mlb_season                   3236 non-null   int64
 70  max_dew_point_v              3236 non-null   float64
 71  max_relative_humidity_v      3236 non-null   float64
 72  max_temperature_v            3236 non-null   float64
 73  max_temperature_s            3236 non-null   float64
 74  max_wind_speed_v             3236 non-null   float64
 75  min_dew_point_v              3236 non-null   float64
 76  min_relative_humidity_v      3236 non-null   float64
 77  min_temperature_v            3236 non-null   float64
 78  min_temperature_s            3236 non-null   float64
 79  min_wind_speed_v             3236 non-null   float64
 80  precipitation_v              3236 non-null   float64
 81  precipitation_s              3236 non-null   float64
 82  rain_v                       3236 non-null   float64
 83  rain_s                       3236 non-null   float64
 84  snow_v                       3236 non-null   float64
 85  snow_s                       3236 non-null   float64
 86  snow_on_ground_v             3236 non-null   float64
 87  non_resident_visitors        3236 non-null   int64
dtypes: bool(1), float64(47), int64(34), object(6)
memory usage: 2.2+ MB

(3236, 88)

In [16]:
# convert data column to date time 
df["date"] = pd.to_datetime(df["date"])

In [17]:
df.head()

,listing_id,date,vacant_days,reserved_days,occupancy,revenue,rate_avg,listing_type,room_type,photos_count,...,min_temperature_s,min_wind_speed_v,precipitation_v,precipitation_s,rain_v,rain_s,snow_v,snow_s,snow_on_ground_v,non_resident_visitors
0,4925824,2025-02-01,28,0,0.0,0,36.3,Private room in townhouse,private_room,7,...,2.85,6.19,54.10,23.65,26.85,17.62,28.99,17.56,6.4,197392
1,4925824,2025-03-01,31,0,0.0,0,35.5,Private room in townhouse,private_room,7,...,2.22,6.19,51.09,22.55,34.94,21.35,16.94,12.79,3.0,251406
2,4925824,2025-04-01,30,0,0.0,0,35.9,Private room in townhouse,private_room,7,...,1.46,5.37,77.41,31.40,69.94,29.82,4.93,5.76,0.5,322508
3,4925824,2025-05-01,31,0,0.0,0,36,Private room in townhouse,private_room,7,...,1.79,3.89,74.07,33.34,73.94,33.46,0.13,0.58,0.0,384863
4,4925824,2025-06-01,30,0,0.0,0,36.5,Private room in townhouse,private_room,7,...,1.02,3.89,81.50,39.88,81.50,39.88,0.00,0.00,0.0,514456

In [18]:
# convert rate_age to numeric number 
df["rate_avg"] = pd.to_numeric(df["rate_avg"], errors="coerce")

In [19]:
df["rate_avg"].head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3236 entries, 0 to 3235
Data columns (total 88 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   listing_id                   3236 non-null   int64
 1   date                         3236 non-null   datetime64[ns]
 2   vacant_days                  3236 non-null   int64
 3   reserved_days                3236 non-null   int64
 4   occupancy                    3236 non-null   float64
 5   revenue                      3236 non-null   int64
 6   rate_avg                     3235 non-null   float64
 7   listing_type                 3236 non-null   object
 8   room_type                    3236 non-null   object
 9   photos_count                 3236 non-null   int64
 10  superhost                    3236 non-null   bool
 11  latitude                     3236 non-null   float64
 12  longitude                    3236 non-null   float64
 13  guests                       3236 non-null   int64
 14  bedrooms                     3236 non-null   int64
 15  beds                         3236 non-null   int64
 16  baths                        3236 non-null   float64
 17  amenities                    3236 non-null   object
 18  min_nights                   3236 non-null   int64
 19  cancellation_policy          3236 non-null   object
 20  cleaning_fee                 3236 non-null   int64
 21  extra_guest_fee              3236 non-null   int64
 22  num_reviews                  3236 non-null   int64
 23  rating_overall               3236 non-null   float64
 24  rating_accuracy              3236 non-null   float64
 25  rating_checkin               3236 non-null   float64
 26  rating_cleanliness           3236 non-null   float64
 27  rating_communication         3236 non-null   float64
 28  rating_location              3236 non-null   float64
 29  rating_value                 3236 non-null   float64
 30  ttm_revenue                  3236 non-null   int64
 31  ttm_revenue_native           3236 non-null   int64
 32  ttm_avg_rate                 3236 non-null   float64
 33  ttm_avg_rate_native          3236 non-null   float64
 34  ttm_occupancy                3236 non-null   float64
 35  ttm_adjusted_occupancy       3236 non-null   float64
 36  ttm_revpar                   3236 non-null   float64
 37  ttm_revpar_native            3236 non-null   float64
 38  ttm_adjusted_revpar          3236 non-null   float64
 39  ttm_adjusted_revpar_native   3236 non-null   float64
 40  ttm_reserved_days            3236 non-null   int64
 41  ttm_blocked_days             3236 non-null   int64
 42  ttm_available_days           3236 non-null   int64
 43  ttm_total_days               3236 non-null   int64
 44  l90d_revenue                 3236 non-null   int64
 45  l90d_revenue_native          3236 non-null   int64
 46  l90d_avg_rate                3236 non-null   float64
 47  l90d_avg_rate_native         3236 non-null   float64
 48  l90d_occupancy               3236 non-null   float64
 49  l90d_adjusted_occupancy      3236 non-null   float64
 50  l90d_revpar                  3236 non-null   float64
 51  l90d_revpar_native           3236 non-null   float64
 52  l90d_adjusted_revpar         3236 non-null   float64
 53  l90d_adjusted_revpar_native  3236 non-null   float64
 54  l90d_reserved_days           3236 non-null   int64
 55  l90d_blocked_days            3236 non-null   int64
 56  l90d_available_days          3236 non-null   int64
 57  l90d_total_days              3236 non-null   int64
 58  Hotel_Occupancy_Percentage   3236 non-null   float64
 59  Average_Daily_Rate           3236 non-null   float64
 60  Revenue_Per_Available_Room   3236 non-null   float64
 61  is_winter                    3236 non-null   int64
 62  is_spring                    3236 non-null   int64
 63  is_summer                    3236 non-null   int64
 64  is_fall                      3236 non-null   int64
 65  num_public_holidays          3236 non-null   int64
 66  num_major_events             3236 non-null   int64
 67  nba_season                   3236 non-null   int64
 68  nhl_season                   3236 non-null   int64
 69  mlb_season                   3236 non-null   int64
 70  max_dew_point_v              3236 non-null   float64
 71  max_relative_humidity_v      3236 non-null   float64
 72  max_temperature_v            3236 non-null   float64
 73  max_temperature_s            3236 non-null   float64
 74  max_wind_speed_v             3236 non-null   float64
 75  min_dew_point_v              3236 non-null   float64
 76  min_relative_humidity_v      3236 non-null   float64
 77  min_temperature_v            3236 non-null   float64
 78  min_temperature_s            3236 non-null   float64
 79  min_wind_speed_v             3236 non-null   float64
 80  precipitation_v              3236 non-null   float64
 81  precipitation_s              3236 non-null   float64
 82  rain_v                       3236 non-null   float64
 83  rain_s                       3236 non-null   float64
 84  snow_v                       3236 non-null   float64
 85  snow_s                       3236 non-null   float64
 86  snow_on_ground_v             3236 non-null   float64
 87  non_resident_visitors        3236 non-null   int64
dtypes: bool(1), datetime64[ns](1), float64(48), int64(34), object(4)
memory usage: 2.2+ MB

In [25]:
df["month"] = df["date"].dt.month
df["month_name"] = df["date"].dt.month_name()

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3236 entries, 0 to 3235
Data columns (total 90 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   listing_id                   3236 non-null   int64
 1   date                         3236 non-null   datetime64[ns]
 2   vacant_days                  3236 non-null   int64
 3   reserved_days                3236 non-null   int64
 4   occupancy                    3236 non-null   float64
 5   revenue                      3236 non-null   int64
 6   rate_avg                     3235 non-null   float64
 7   listing_type                 3236 non-null   object
 8   room_type                    3236 non-null   object
 9   photos_count                 3236 non-null   int64
 10  superhost                    3236 non-null   bool
 11  latitude                     3236 non-null   float64
 12  longitude                    3236 non-null   float64
 13  guests                       3236 non-null   int64
 14  bedrooms                     3236 non-null   int64
 15  beds                         3236 non-null   int64
 16  baths                        3236 non-null   float64
 17  amenities                    3236 non-null   object
 18  min_nights                   3236 non-null   int64
 19  cancellation_policy          3236 non-null   object
 20  cleaning_fee                 3236 non-null   int64
 21  extra_guest_fee              3236 non-null   int64
 22  num_reviews                  3236 non-null   int64
 23  rating_overall               3236 non-null   float64
 24  rating_accuracy              3236 non-null   float64
 25  rating_checkin               3236 non-null   float64
 26  rating_cleanliness           3236 non-null   float64
 27  rating_communication         3236 non-null   float64
 28  rating_location              3236 non-null   float64
 29  rating_value                 3236 non-null   float64
 30  ttm_revenue                  3236 non-null   int64
 31  ttm_revenue_native           3236 non-null   int64
 32  ttm_avg_rate                 3236 non-null   float64
 33  ttm_avg_rate_native          3236 non-null   float64
 34  ttm_occupancy                3236 non-null   float64
 35  ttm_adjusted_occupancy       3236 non-null   float64
 36  ttm_revpar                   3236 non-null   float64
 37  ttm_revpar_native            3236 non-null   float64
 38  ttm_adjusted_revpar          3236 non-null   float64
 39  ttm_adjusted_revpar_native   3236 non-null   float64
 40  ttm_reserved_days            3236 non-null   int64
 41  ttm_blocked_days             3236 non-null   int64
 42  ttm_available_days           3236 non-null   int64
 43  ttm_total_days               3236 non-null   int64
 44  l90d_revenue                 3236 non-null   int64
 45  l90d_revenue_native          3236 non-null   int64
 46  l90d_avg_rate                3236 non-null   float64
 47  l90d_avg_rate_native         3236 non-null   float64
 48  l90d_occupancy               3236 non-null   float64
 49  l90d_adjusted_occupancy      3236 non-null   float64
 50  l90d_revpar                  3236 non-null   float64
 51  l90d_revpar_native           3236 non-null   float64
 52  l90d_adjusted_revpar         3236 non-null   float64
 53  l90d_adjusted_revpar_native  3236 non-null   float64
 54  l90d_reserved_days           3236 non-null   int64
 55  l90d_blocked_days            3236 non-null   int64
 56  l90d_available_days          3236 non-null   int64
 57  l90d_total_days              3236 non-null   int64
 58  Hotel_Occupancy_Percentage   3236 non-null   float64
 59  Average_Daily_Rate           3236 non-null   float64
 60  Revenue_Per_Available_Room   3236 non-null   float64
 61  is_winter                    3236 non-null   int64
 62  is_spring                    3236 non-null   int64
 63  is_summer                    3236 non-null   int64
 64  is_fall                      3236 non-null   int64
 65  num_public_holidays          3236 non-null   int64
 66  num_major_events             3236 non-null   int64
 67  nba_season                   3236 non-null   int64
 68  nhl_season                   3236 non-null   int64
 69  mlb_season                   3236 non-null   int64
 70  max_dew_point_v              3236 non-null   float64
 71  max_relative_humidity_v      3236 non-null   float64
 72  max_temperature_v            3236 non-null   float64
 73  max_temperature_s            3236 non-null   float64
 74  max_wind_speed_v             3236 non-null   float64
 75  min_dew_point_v              3236 non-null   float64
 76  min_relative_humidity_v      3236 non-null   float64
 77  min_temperature_v            3236 non-null   float64
 78  min_temperature_s            3236 non-null   float64
 79  min_wind_speed_v             3236 non-null   float64
 80  precipitation_v              3236 non-null   float64
 81  precipitation_s              3236 non-null   float64
 82  rain_v                       3236 non-null   float64
 83  rain_s                       3236 non-null   float64
 84  snow_v                       3236 non-null   float64
 85  snow_s                       3236 non-null   float64
 86  snow_on_ground_v             3236 non-null   float64
 87  non_resident_visitors        3236 non-null   int64
 88  month                        3236 non-null   int32
 89  month_name                   3236 non-null   object
dtypes: bool(1), datetime64[ns](1), float64(48), int32(1), int64(34), object(5)
memory usage: 2.2+ MB

In [49]:
month_dummies = pd.get_dummies(df["month_name"], prefix="is")

month_dummies = month_dummies.astype(int)

month_dummies.columns = month_dummies.columns.str.lower()

df = pd.concat([df, month_dummies], axis=1)

In [53]:
df.filter(like="is_").head()

,is_winter,is_spring,is_summer,is_fall,is_april,is_august,is_february,is_july,is_june,is_march,is_may,is_november,is_october,is_september
0,1,0,0,0,0,0,1,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,1,0,0,0,0
2,0,1,0,0,1,0,0,0,0,0,0,0,0,0
3,0,1,0,0,0,0,0,0,0,0,1,0,0,0
4,0,0,1,0,0,0,0,0,1,0,0,0,0,0

In [51]:
# Removes december to avoid dummy trap variable 
df = df.drop(columns=["is_december"])

In [54]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3236 entries, 0 to 3235
Data columns (total 100 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   listing_id                   3236 non-null   int64
 1   date                         3236 non-null   datetime64[ns]
 2   vacant_days                  3236 non-null   int64
 3   reserved_days                3236 non-null   int64
 4   occupancy                    3236 non-null   float64
 5   revenue                      3236 non-null   int64
 6   rate_avg                     3235 non-null   float64
 7   listing_type                 3236 non-null   object
 8   room_type                    3236 non-null   object
 9   photos_count                 3236 non-null   int64
 10  superhost                    3236 non-null   bool
 11  latitude                     3236 non-null   float64
 12  longitude                    3236 non-null   float64
 13  guests                       3236 non-null   int64
 14  bedrooms                     3236 non-null   int64
 15  beds                         3236 non-null   int64
 16  baths                        3236 non-null   float64
 17  amenities                    3236 non-null   object
 18  min_nights                   3236 non-null   int64
 19  cancellation_policy          3236 non-null   object
 20  cleaning_fee                 3236 non-null   int64
 21  extra_guest_fee              3236 non-null   int64
 22  num_reviews                  3236 non-null   int64
 23  rating_overall               3236 non-null   float64
 24  rating_accuracy              3236 non-null   float64
 25  rating_checkin               3236 non-null   float64
 26  rating_cleanliness           3236 non-null   float64
 27  rating_communication         3236 non-null   float64
 28  rating_location              3236 non-null   float64
 29  rating_value                 3236 non-null   float64
 30  ttm_revenue                  3236 non-null   int64
 31  ttm_revenue_native           3236 non-null   int64
 32  ttm_avg_rate                 3236 non-null   float64
 33  ttm_avg_rate_native          3236 non-null   float64
 34  ttm_occupancy                3236 non-null   float64
 35  ttm_adjusted_occupancy       3236 non-null   float64
 36  ttm_revpar                   3236 non-null   float64
 37  ttm_revpar_native            3236 non-null   float64
 38  ttm_adjusted_revpar          3236 non-null   float64
 39  ttm_adjusted_revpar_native   3236 non-null   float64
 40  ttm_reserved_days            3236 non-null   int64
 41  ttm_blocked_days             3236 non-null   int64
 42  ttm_available_days           3236 non-null   int64
 43  ttm_total_days               3236 non-null   int64
 44  l90d_revenue                 3236 non-null   int64
 45  l90d_revenue_native          3236 non-null   int64
 46  l90d_avg_rate                3236 non-null   float64
 47  l90d_avg_rate_native         3236 non-null   float64
 48  l90d_occupancy               3236 non-null   float64
 49  l90d_adjusted_occupancy      3236 non-null   float64
 50  l90d_revpar                  3236 non-null   float64
 51  l90d_revpar_native           3236 non-null   float64
 52  l90d_adjusted_revpar         3236 non-null   float64
 53  l90d_adjusted_revpar_native  3236 non-null   float64
 54  l90d_reserved_days           3236 non-null   int64
 55  l90d_blocked_days            3236 non-null   int64
 56  l90d_available_days          3236 non-null   int64
 57  l90d_total_days              3236 non-null   int64
 58  Hotel_Occupancy_Percentage   3236 non-null   float64
 59  Average_Daily_Rate           3236 non-null   float64
 60  Revenue_Per_Available_Room   3236 non-null   float64
 61  is_winter                    3236 non-null   int64
 62  is_spring                    3236 non-null   int64
 63  is_summer                    3236 non-null   int64
 64  is_fall                      3236 non-null   int64
 65  num_public_holidays          3236 non-null   int64
 66  num_major_events             3236 non-null   int64
 67  nba_season                   3236 non-null   int64
 68  nhl_season                   3236 non-null   int64
 69  mlb_season                   3236 non-null   int64
 70  max_dew_point_v              3236 non-null   float64
 71  max_relative_humidity_v      3236 non-null   float64
 72  max_temperature_v            3236 non-null   float64
 73  max_temperature_s            3236 non-null   float64
 74  max_wind_speed_v             3236 non-null   float64
 75  min_dew_point_v              3236 non-null   float64
 76  min_relative_humidity_v      3236 non-null   float64
 77  min_temperature_v            3236 non-null   float64
 78  min_temperature_s            3236 non-null   float64
 79  min_wind_speed_v             3236 non-null   float64
 80  precipitation_v              3236 non-null   float64
 81  precipitation_s              3236 non-null   float64
 82  rain_v                       3236 non-null   float64
 83  rain_s                       3236 non-null   float64
 84  snow_v                       3236 non-null   float64
 85  snow_s                       3236 non-null   float64
 86  snow_on_ground_v             3236 non-null   float64
 87  non_resident_visitors        3236 non-null   int64
 88  month                        3236 non-null   int32
 89  month_name                   3236 non-null   object
 90  is_april                     3236 non-null   int64
 91  is_august                    3236 non-null   int64
 92  is_february                  3236 non-null   int64
 93  is_july                      3236 non-null   int64
 94  is_june                      3236 non-null   int64
 95  is_march                     3236 non-null   int64
 96  is_may                       3236 non-null   int64
 97  is_november                  3236 non-null   int64
 98  is_october                   3236 non-null   int64
 99  is_september                 3236 non-null   int64
dtypes: bool(1), datetime64[ns](1), float64(48), int32(1), int64(44), object(5)
memory usage: 2.4+ MB

,listing_id,date,vacant_days,reserved_days,occupancy,revenue,rate_avg,listing_type,room_type,photos_count,...,is_april,is_august,is_february,is_july,is_june,is_march,is_may,is_november,is_october,is_september
0,4925824,2025-02-01,28,0,0.0,0,36.3,Private room in townhouse,private_room,7,...,0,0,1,0,0,0,0,0,0,0
1,4925824,2025-03-01,31,0,0.0,0,35.5,Private room in townhouse,private_room,7,...,0,0,0,0,0,1,0,0,0,0
2,4925824,2025-04-01,30,0,0.0,0,35.9,Private room in townhouse,private_room,7,...,1,0,0,0,0,0,0,0,0,0
3,4925824,2025-05-01,31,0,0.0,0,36.0,Private room in townhouse,private_room,7,...,0,0,0,0,0,0,1,0,0,0
4,4925824,2025-06-01,30,0,0.0,0,36.5,Private room in townhouse,private_room,7,...,0,0,0,0,1,0,0,0,0,0

In [55]:
df["superhost"] = df["superhost"].astype(int)

In [59]:
df["superhost"].head(50)

0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
30    0
31    0
32    0
33    0
34    0
35    0
36    0
37    0
38    0
39    0
40    0
41    0
42    0
43    0
44    0
45    0
46    0
47    0
48    0
49    0
Name: superhost, dtype: int64

In [61]:
df["has_free_parking"] = df["amenities"].str.contains("free parking", case=False, na=False).astype(int)

df["has_gym"] = df["amenities"].str.contains("gym", case=False, na=False).astype(int)

df["has_pool"] = df["amenities"].str.contains("pool", case=False, na=False).astype(int)

In [62]:
df[["has_free_parking","has_gym","has_pool"]].head()

   has_free_parking  has_gym  has_pool
0                 1        0         0
1                 1        0         0
2                 1        0         0
3                 1        0         0
4                 1        0         0

In [63]:
# after creating dummy columns drop the amenities column 
df = df.drop(columns=["amenities"])

In [64]:
# check remaing text colums 
df.select_dtypes(include="object").columns

Index(['listing_type', 'room_type', 'cancellation_policy', 'month_name'], dtype='object')

In [65]:
df = df.drop(columns=["month_name"])

In [66]:
categorical_cols = ["listing_type", "room_type", "cancellation_policy"]
# create dummy vars and drop one to avoid dummy var trap
df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

In [69]:
df.filter(regex="listing_type|room_type|cancellation_policy").head()

,listing_type_Entire condo,listing_type_Entire condominium,listing_type_Entire guest suite,listing_type_Entire guesthouse,listing_type_Entire home,listing_type_Entire house,listing_type_Entire loft,listing_type_Entire place,listing_type_Entire rental unit,listing_type_Entire townhouse,...,listing_type_Private room in home,listing_type_Private room in loft,listing_type_Private room in rental unit,listing_type_Private room in townhouse,room_type_private_room,cancellation_policy_Flexible,cancellation_policy_Limited,cancellation_policy_Moderate,cancellation_policy_Strict,cancellation_policy_Super Strict 30 Days
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,1,0,0,1,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,1,0,0,1,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,1,0,0,1,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,1,0,0,1,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,1,0,0,1,0,0

In [68]:
df = df.apply(lambda col: col.astype(int) if col.dtype == "bool" else col)

In [70]:
df.head()

,listing_id,date,vacant_days,reserved_days,occupancy,revenue,rate_avg,photos_count,superhost,latitude,...,listing_type_Private room in home,listing_type_Private room in loft,listing_type_Private room in rental unit,listing_type_Private room in townhouse,room_type_private_room,cancellation_policy_Flexible,cancellation_policy_Limited,cancellation_policy_Moderate,cancellation_policy_Strict,cancellation_policy_Super Strict 30 Days
0,4925824,2025-02-01,28,0,0.0,0,36.3,7,1,43.6483,...,0,0,0,1,1,0,0,1,0,0
1,4925824,2025-03-01,31,0,0.0,0,35.5,7,1,43.6483,...,0,0,0,1,1,0,0,1,0,0
2,4925824,2025-04-01,30,0,0.0,0,35.9,7,1,43.6483,...,0,0,0,1,1,0,0,1,0,0
3,4925824,2025-05-01,31,0,0.0,0,36.0,7,1,43.6483,...,0,0,0,1,1,0,0,1,0,0
4,4925824,2025-06-01,30,0,0.0,0,36.5,7,1,43.6483,...,0,0,0,1,1,0,0,1,0,0

In [72]:
print(df.shape)

(3236, 124)

In [74]:
df.duplicated().sum()

np.int64(0)

In [76]:
df.isnull().sum().sort_values(ascending=False).head(20)

rate_avg                 1
listing_id               0
rain_v                   0
is_may                   0
is_march                 0
is_june                  0
is_july                  0
is_february              0
is_august                0
is_april                 0
month                    0
non_resident_visitors    0
snow_on_ground_v         0
snow_s                   0
snow_v                   0
rain_s                   0
precipitation_s          0
is_october               0
precipitation_v          0
min_wind_speed_v         0
dtype: int64

In [77]:
df["rate_avg"] = df["rate_avg"].fillna(df["rate_avg"].median())

In [78]:
df.isnull().sum().sort_values(ascending=False).head(20)

listing_id               0
rain_v                   0
is_may                   0
is_march                 0
is_june                  0
is_july                  0
is_february              0
is_august                0
is_april                 0
month                    0
non_resident_visitors    0
snow_on_ground_v         0
snow_s                   0
snow_v                   0
rain_s                   0
precipitation_s          0
date                     0
precipitation_v          0
min_wind_speed_v         0
min_temperature_s        0
dtype: int64

In [85]:
# if num of bedrooms or beds is greater than zero and current guests = 1 assume 1 guest
df.loc[(df["guests"] == 0) & ((df["beds"] > 0) | (df["bedrooms"] > 0)),
    "guests"] = 1

In [82]:
# If bedrooms are 0 but beds exist could mean studio or private room so set bedrooms to 1
df.loc[(df["bedrooms"] == 0) & (df["beds"] > 0), "bedrooms"] = 1

In [86]:
df[(df["guests"] == 0)][["guests","bedrooms","beds"]].head()

Empty DataFrame
Columns: [guests, bedrooms, beds]
Index: []

In [88]:
#esnure guests is never zero if guests is listed as zero replace with 1
df.loc[df["guests"] < 1, "guests"] = 1

In [91]:
df.shape
df.head()

,listing_id,date,vacant_days,reserved_days,occupancy,revenue,rate_avg,photos_count,superhost,latitude,...,listing_type_Private room in home,listing_type_Private room in loft,listing_type_Private room in rental unit,listing_type_Private room in townhouse,room_type_private_room,cancellation_policy_Flexible,cancellation_policy_Limited,cancellation_policy_Moderate,cancellation_policy_Strict,cancellation_policy_Super Strict 30 Days
0,4925824,2025-02-01,28,0,0.0,0,36.3,7,1,43.6483,...,0,0,0,1,1,0,0,1,0,0
1,4925824,2025-03-01,31,0,0.0,0,35.5,7,1,43.6483,...,0,0,0,1,1,0,0,1,0,0
2,4925824,2025-04-01,30,0,0.0,0,35.9,7,1,43.6483,...,0,0,0,1,1,0,0,1,0,0
3,4925824,2025-05-01,31,0,0.0,0,36.0,7,1,43.6483,...,0,0,0,1,1,0,0,1,0,0
4,4925824,2025-06-01,30,0,0.0,0,36.5,7,1,43.6483,...,0,0,0,1,1,0,0,1,0,0

In [93]:
print("DATASET SHAPE")
print(df.shape)

print("\nFIRST 5 ROWS")
print(df.head())

print("\nCOLUMN INFO")
print(df.info())

print("\nTOP 20 MISSING VALUES")
print(df.isnull().sum().sort_values(ascending=False).head(20))

print("\nNUMBER OF DUPLICATE ROWS")
print(df.duplicated().sum())

print("\nNUMERIC SUMMARY")
print(df.describe().T)

print("\nOBJECT (CATEGORICAL) COLUMNS")
print(df.select_dtypes(include="object").columns)

print("\nTOTAL NUMBER OF FEATURES")
print(len(df.columns))

DATASET SHAPE
(3236, 124)

FIRST 5 ROWS
   listing_id       date  vacant_days  reserved_days  occupancy  revenue  \
0     4925824 2025-02-01           28              0        0.0        0
1     4925824 2025-03-01           31              0        0.0        0
2     4925824 2025-04-01           30              0        0.0        0
3     4925824 2025-05-01           31              0        0.0        0
4     4925824 2025-06-01           30              0        0.0        0

   rate_avg  photos_count  superhost  latitude  ...  \
0      36.3             7          1   43.6483  ...
1      35.5             7          1   43.6483  ...
2      35.9             7          1   43.6483  ...
3      36.0             7          1   43.6483  ...
4      36.5             7          1   43.6483  ...

   listing_type_Private room in home  listing_type_Private room in loft  \
0                                  0                                  0
1                                  0                                  0
2                                  0                                  0
3                                  0                                  0
4                                  0                                  0

   listing_type_Private room in rental unit  \
0                                         0
1                                         0
2                                         0
3                                         0
4                                         0

   listing_type_Private room in townhouse  room_type_private_room  \
0                                       1                       1
1                                       1                       1
2                                       1                       1
3                                       1                       1
4                                       1                       1

   cancellation_policy_Flexible  cancellation_policy_Limited  \
0                             0                            0
1                             0                            0
2                             0                            0
3                             0                            0
4                             0                            0

   cancellation_policy_Moderate  cancellation_policy_Strict  \
0                             1                           0
1                             1                           0
2                             1                           0
3                             1                           0
4                             1                           0

   cancellation_policy_Super Strict 30 Days
0                                         0
1                                         0
2                                         0
3                                         0
4                                         0

[5 rows x 124 columns]

COLUMN INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3236 entries, 0 to 3235
Columns: 124 entries, listing_id to cancellation_policy_Super Strict 30 Days
dtypes: datetime64[ns](1), float64(48), int32(1), int64(74)
memory usage: 3.0 MB
None

TOP 20 MISSING VALUES
listing_id               0
rain_v                   0
is_may                   0
is_march                 0
is_june                  0
is_july                  0
is_february              0
is_august                0
is_april                 0
month                    0
non_resident_visitors    0
snow_on_ground_v         0
snow_s                   0
snow_v                   0
rain_s                   0
precipitation_s          0
date                     0
precipitation_v          0
min_wind_speed_v         0
min_temperature_s        0
dtype: int64

NUMBER OF DUPLICATE ROWS
0

NUMERIC SUMMARY
                                           count  \
listing_id                                3236.0
date                                        3236
vacant_days                               3236.0
reserved_days                             3236.0
occupancy                                 3236.0
...                                          ...
cancellation_policy_Flexible              3236.0
cancellation_policy_Limited               3236.0
cancellation_policy_Moderate              3236.0
cancellation_policy_Strict                3236.0
cancellation_policy_Super Strict 30 Days  3236.0

                                                                   mean  \
listing_id                                               3383197.347033
date                                      2025-06-30 15:42:56.514215424
vacant_days                                                   19.483313
reserved_days                                                 10.879481
occupancy                                                      0.357436
...                                                                 ...
cancellation_policy_Flexible                                   0.106304
cancellation_policy_Limited                                    0.013597
cancellation_policy_Moderate                                   0.209209
cancellation_policy_Strict                                     0.199011
cancellation_policy_Super Strict 30 Days                       0.006799

                                                          min  \
listing_id                                            26654.0
date                                      2025-02-01 00:00:00
vacant_days                                               0.0
reserved_days                                             0.0
occupancy                                                 0.0
...                                                       ...
cancellation_policy_Flexible                              0.0
cancellation_policy_Limited                               0.0
cancellation_policy_Moderate                              0.0
cancellation_policy_Strict                                0.0
cancellation_policy_Super Strict 30 Days                  0.0

                                                          25%  \
listing_id                                          1370412.0
date                                      2025-04-01 00:00:00
vacant_days                                               9.0
reserved_days                                             0.0
occupancy                                                 0.0
...                                                       ...
cancellation_policy_Flexible                              0.0
cancellation_policy_Limited                               0.0
cancellation_policy_Moderate                              0.0
cancellation_policy_Strict                                0.0
cancellation_policy_Super Strict 30 Days                  0.0

                                                          50%  \
listing_id                                          3581243.0
date                                      2025-07-01 00:00:00
vacant_days                                              24.0
reserved_days                                             7.0
occupancy                                               0.226
...                                                       ...
cancellation_policy_Flexible                              0.0
cancellation_policy_Limited                               0.0
cancellation_policy_Moderate                              0.0
cancellation_policy_Strict                                0.0
cancellation_policy_Super Strict 30 Days                  0.0

                                                          75%  \
listing_id                                          5289620.0
date                                      2025-10-01 00:00:00
vacant_days                                              30.0
reserved_days                                            22.0
occupancy                                                0.71
...                                                       ...
cancellation_policy_Flexible                              0.0
cancellation_policy_Limited                               0.0
cancellation_policy_Moderate                              0.0
cancellation_policy_Strict                                0.0
cancellation_policy_Super Strict 30 Days                  0.0

                                                          max             std
listing_id                                          6728860.0  2072034.254845
date                                      2025-12-01 00:00:00             NaN
vacant_days                                              31.0       11.342226
reserved_days                                            31.0       11.398839
occupancy                                                 1.0        0.373889
...                                                       ...             ...
cancellation_policy_Flexible                              1.0        0.308274
cancellation_policy_Limited                               1.0        0.115829
cancellation_policy_Moderate                              1.0        0.406807
cancellation_policy_Strict                                1.0        0.399318
cancellation_policy_Super Strict 30 Days                  1.0        0.082185

[124 rows x 8 columns]

OBJECT (CATEGORICAL) COLUMNS
Index([], dtype='object')

TOTAL NUMBER OF FEATURES
124